version: '3.8'

services:
  strmify:
    image: ghcr.io/nchungdev/strmify:latest
    container_name: strmify
    ports:
      - "3030:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - INTRO_DB_PATH=/introskipper/introskipper.db
      - PUID=1000
      - PGID=100
    env_file:
      - .env
    volumes:
      - /srv/dev-disk-by-uuid-98bd3ebc-514a-4108-ac09-155de8462a10/strmify:/config
      - /srv/mergerfs/MainPool/Phim:/srv/media
      - /home/chungnh/appdata/jellyfin/data/data/introskipper:/introskipper
    restart: always
